### ISSUE TITLE
Null pointer exception for one device in automated Play tests

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner-android#105]
When the Play store ran automated tests across multiple devices, one device encountered a null pointer exception attempting to access a map member. Determine if there is something to guard against to prevent this error.

<Details>
FATAL EXCEPTION: ControllerMessenger
Process: org.gophillygo.app, PID: 11902
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
	at org.gophillygo.app.activities.MapsActivity.selectedAttractionInfo(MapsActivity.java:247)
	at org.gophillygo.app.activities.MapsActivity.reloadSelectedAttraction(MapsActivity.java:241)
	at org.gophillygo.app.activities.MapsActivity.loadData(MapsActivity.java:180)
	at org.gophillygo.app.activities.FilterableListActivity.setFilter(FilterableListActivity.java:86)
	at org.gophillygo.app.activities.FilterableListActivity.toggleLiked(FilterableListActivity.java:107)
	at org.gophillygo.app.databinding.FilterButtonBarBindingImpl._internalCallbackOnClick(FilterButtonBarBindingImpl.java:230)
	at org.gophillygo.app.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
	at android.view.View.performClick(View.java:5207)
	at android.widget.CompoundButton.performClick(CompoundButton.java:122)
	at android.view.View$PerformClick.run(View.java:21168)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.support.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at android.support.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:142)
	at android.support.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:134)
	at android.support.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
	at android.support.test.espresso.action.MotionEvents.a(MotionEvents.java:74)
	at android.support.test.espresso.action.MotionEvents.a(MotionEvents.java:52)
	at android.support.test.espresso.action.Tap.c(Tap.java:9)
	at android.support.test.espresso.action.Tap.a(Tap.java:19)
	at android.support.test.espresso.action.Tap$1.b(Tap.java:2)
	at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at android.support.test.espresso.ViewInteraction.a(ViewInteraction.java:78)
	at android.support.test.espresso.ViewInteraction.a(ViewInteraction.java:94)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
</Detaills>

**Comment by flibbertigibbet** [comment]
Fixed in the last automated test run:
![image](https://user-images.githubusercontent.com/960264/41796710-92b62aec-7635-11e8-8e1a-3de597be990c.png)
